runtime: python
env: flex
entrypoint: gunicorn --reload wsgi:app -b :$PORT --log-level LEVEL


runtime_config:
  python_version: 3.7

env_variables:
  CLOUD_STORAGE_BUCKET: <your-cloud-storage-bucket>
